# Generated by Django 5.1.5 on 2025-01-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('df', 'draft'), ('pb', 'published')], default='df', max_length=10),
        ),
    ]
