# Generated by Django 5.1.5 on 2025-01-25 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish_at',)},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='publish_idx',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='publish_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['publish_at'], name='publish_idx'),
        ),
    ]
